# Import Library & Dataset

In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt

In [ ]:
df = pd.read_csv('/content/Sample - Superstore.csv', encoding='latin1')

In [ ]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [ ]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

In [ ]:
df = df.drop('Product Name', axis=1)
df = df.drop('Row ID', axis=1)
df = df.drop('Customer Name', axis=1)
df = df.drop('Segment', axis=1)
df = df.drop('Postal Code', axis=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9993 entries, 0 to 9993
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      9993 non-null   object
 1   Order Date    9993 non-null   datetime64[ns]
 2   Ship Date     9993 non-null   datetime64[ns]
 3   Ship Mode     9993 non-null   object
 4   Customer ID   9993 non-null   object
 5   Country       9993 non-null   object
 6   City          9993 non-null   object
 7   State         9993 non-null   object
 8   Region        9993 non-null   object
 9   Product ID    9993 non-null   object
 10  Category      9993 non-null   object
 11  Sub-Category  9993 non-null   object
 12  Sales         9993 non-null   float64
 13  Quantity      9993 non-null   int64
 14  Discount      9993 non-null   float64
 15  Profit        9993 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(1), object(10)
memory usage: 1.3+ MB

In [ ]:
print(df[ df.duplicated(keep=False)] )

            Order ID Order Date  Ship Date       Ship Mode Customer ID  \
3405  US-2014-150119 2014-04-23 2014-04-27  Standard Class    LB-16795
3406  US-2014-150119 2014-04-23 2014-04-27  Standard Class    LB-16795

            Country      City State Region       Product ID   Category  \
3405  United States  Columbus  Ohio   East  FUR-CH-10002965  Furniture
3406  United States  Columbus  Ohio   East  FUR-CH-10002965  Furniture

     Sub-Category    Sales  Quantity  Discount   Profit
3405       Chairs  281.372         2       0.3 -12.0588
3406       Chairs  281.372         2       0.3 -12.0588

In [ ]:
df = df.drop_duplicates()

In [ ]:
print(df.duplicated().sum())

0

In [ ]:
dieu_kien = df[ ((df['Sales']<=0) | (df['Quantity']<=0) | (df['Discount']<0)) == True]
so_luong_dong = dieu_kien.shape[0]
print("Số lượng dòng:", so_luong_dong)

Số lượng dòng: 0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9993 entries, 0 to 9993
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      9993 non-null   object
 1   Order Date    9993 non-null   datetime64[ns]
 2   Ship Date     9993 non-null   datetime64[ns]
 3   Ship Mode     9993 non-null   object
 4   Customer ID   9993 non-null   object
 5   Country       9993 non-null   object
 6   City          9993 non-null   object
 7   State         9993 non-null   object
 8   Region        9993 non-null   object
 9   Product ID    9993 non-null   object
 10  Category      9993 non-null   object
 11  Sub-Category  9993 non-null   object
 12  Sales         9993 non-null   float64
 13  Quantity      9993 non-null   int64
 14  Discount      9993 non-null   float64
 15  Profit        9993 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(1), object(10)
memory usage: 1.3+ MB

In [ ]:
df.to_csv('SuperStore.csv', index=False)

## RFM

In [ ]:
RFM = df.groupby('Customer ID').agg(Max_InvoiceDate = ("Order Date", "max"), F = ("Order ID", "nunique"), M = ("Sales", "sum")).reset_index()

In [ ]:
RFM['Today'] = pd.to_datetime("2025-07-26")

In [ ]:
RFM["R"] = (RFM["Today"] - RFM["Max_InvoiceDate"]).dt.days

In [ ]:
RFM = RFM[["Customer ID", "R", "F", "M"]]
RFM

    Customer ID     R   F         M
0      AA-10315  2949   5  5563.560
1      AA-10375  2784   9  1056.390
2      AA-10480  3024   4  1790.512
3      AA-10645  2820   6  5086.935
4      AB-10015  3180   3   886.156
..          ...   ...  ..       ...
788    XP-21865  2808  11  2374.658
789    YC-21895  2769   5  5454.350
790    YS-21880  2774   8  6720.444
791    ZC-21910  2819  13  8025.707
792    ZD-21925  2967   5  1493.944

[793 rows x 4 columns]

In [ ]:
RFM['F_Score'] = pd.qcut(RFM['F'].rank(method = 'first'), 5, labels = [1, 2, 3, 4, 5])
RFM['M_Score'] = pd.qcut(RFM['M'].rank(method = 'first'), 5, labels = [1, 2, 3, 4, 5])
RFM['R_Score'] = pd.qcut(RFM['R'].rank(method = 'first'), 5, labels = [5, 4, 3, 2, 1])

In [ ]:
RFM['RFM_Score'] = RFM['R_Score'].astype(str) + RFM['F_Score'].astype(str) + RFM['M_Score'].astype(str)

In [ ]:
rfm_ranking = pd.read_csv('/content/RankRFM.xlsx - Sheet1.csv')

In [ ]:
rfm_ranking['Scores'] = rfm_ranking['Scores'].str.replace(', ', ',').str.split(",")

In [ ]:
rfm_ranking_new = rfm_ranking.explode("Scores").reset_index()

In [ ]:
rfm_ranking_new

     index         Segment Scores
0        0       Champions    555
1        0       Champions    554
2        0       Champions    544
3        0       Champions    545
4        0       Champions    454
..     ...             ...    ...
120     10  Lost customers    112
121     10  Lost customers    121
122     10  Lost customers    131
123     10  Lost customers    141
124     10  Lost customers    151

[125 rows x 3 columns]

In [ ]:
RFM = RFM.merge(rfm_ranking_new, how = "left", left_on = "RFM_Score", right_on="Scores")
RFM

,Customer ID,R,F,M,F_Score,M_Score,R_Score,RFM_Score,index,Segment,Scores
0,AA-10315,2949,5,5563.560,2,5,2,225,7,At Risk,225
1,AA-10375,2784,9,1056.390,5,2,5,552,2,Potential Loyalist,552
2,AA-10480,3024,4,1790.512,1,3,1,113,8,Cannot Lose Them,113
3,AA-10645,2820,6,5086.935,3,5,3,335,1,Loyal,335
4,AB-10015,3180,3,886.156,1,1,1,111,10,Lost customers,111
...,...,...,...,...,...,...,...,...,...,...,...
788,XP-21865,2808,11,2374.658,5,3,4,453,2,Potential Loyalist,453
789,YC-21895,2769,5,5454.350,3,5,5,535,5,Need Attention,535
790,YS-21880,2774,8,6720.444,4,5,5,545,0,Champions,545
791,ZC-21910,2819,13,8025.707,5,5,3,355,1,Loyal,355
792,ZD-21925,2967,5,1493.944,3,2,2,232,9,Hibernating customers,232

In [ ]:
RFM = RFM.drop(columns = ["index"])

In [ ]:
RFM

,Customer ID,R,F,M,F_Score,M_Score,R_Score,RFM_Score,Segment,Scores
0,AA-10315,2949,5,5563.560,2,5,2,225,At Risk,225
1,AA-10375,2784,9,1056.390,5,2,5,552,Potential Loyalist,552
2,AA-10480,3024,4,1790.512,1,3,1,113,Cannot Lose Them,113
3,AA-10645,2820,6,5086.935,3,5,3,335,Loyal,335
4,AB-10015,3180,3,886.156,1,1,1,111,Lost customers,111
...,...,...,...,...,...,...,...,...,...,...
788,XP-21865,2808,11,2374.658,5,3,4,453,Potential Loyalist,453
789,YC-21895,2769,5,5454.350,3,5,5,535,Need Attention,535
790,YS-21880,2774,8,6720.444,4,5,5,545,Champions,545
791,ZC-21910,2819,13,8025.707,5,5,3,355,Loyal,355
792,ZD-21925,2967,5,1493.944,3,2,2,232,Hibernating customers,232

In [ ]:
set(RFM['F_Score'])

In [ ]:
sns.boxplot(x="Sales", data=df)

In [ ]:
df[ df['Sales'] > 10000]

In [ ]:
print( df['Order ID'].duplicated().sum())

In [ ]:
df_brandow = df[ df['Customer Name']=='Cassandra Brandow']

In [ ]:
df_brandow